"""
Deep Tensor Consistency Test
=============================
Compares tensors generated by Python (tensor_utils_mastery.py)
against tensors generated by C++ (game.cpp via MCTS engine).

This is the critical test for C++/Python alignment.
"""

import os
import sys
import numpy as np

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

import ludo_cpp
from src.tensor_utils_mastery import state_to_tensor_mastery


def create_test_state(scenario):
    """Create a game state for a specific test scenario."""
    state = ludo_cpp.create_initial_state()
    
    if scenario == "initial":
        # Fresh game, dice=6, player 0
        state.current_dice_roll = 6
        return state
    
    elif scenario == "mid_game":
        # Mid-game: mixed positions
        state.current_player = 0
        state.current_dice_roll = 3
        state.player_positions[0][0] = 10
        state.player_positions[0][1] = 25
        state.player_positions[0][2] = -1  # base
        state.player_positions[0][3] = 52  # home run
        
        state.player_positions[1][0] = 5
        state.player_positions[1][1] = 15
        state.player_positions[1][2] = 99  # home
        state.player_positions[1][3] = -1
        
        state.scores[0] = 0
        state.scores[1] = 1
        return state
    
    elif scenario == "player1_view":
        # Same as mid_game but from player 1's perspective
        state.current_player = 1
        state.current_dice_roll = 4
        state.player_positions[0][0] = 10
        state.player_positions[0][1] = 25
        state.player_positions[1][0] = 5
        state.player_positions[1][1] = 15
        return state
    
    elif scenario == "end_game":
        # Near end: player 0 has 3 home
        state.current_player = 0
        state.current_dice_roll = 2
        state.player_positions[0][0] = 99
        state.player_positions[0][1] = 99
        state.player_positions[0][2] = 99
        state.player_positions[0][3] = 54  # about to finish
        state.scores[0] = 3
        return state
    
    return state


def get_cpp_tensor(state):
    """Get tensor from C++ via MCTS engine."""
    mcts = ludo_cpp.MCTSEngine(1, 3.0, 0.0, 0.0)  # No Dirichlet noise
    mcts.set_roots([state])
    mcts.select_leaves(parallel_sims=1)
    tensors = mcts.get_leaf_tensors()
    
    if tensors.shape[0] == 0:
        # Terminal state or no leaves
        return None
    
    return tensors[0]  # Shape (21, 15, 15)


def get_python_tensor(state):
    """Get tensor from Python."""
    return state_to_tensor_mastery(state).numpy()


def compare_channels(py_tensor, cpp_tensor, channel, name, tolerance=0.01):
    """Compare a specific channel between Python and C++ tensors."""
    py_ch = py_tensor[channel]
    cpp_ch = cpp_tensor[channel]
    
    diff = np.abs(py_ch - cpp_ch)
    max_diff = diff.max()
    
    if max_diff > tolerance:
        # Find where the differences are
        diff_locs = np.argwhere(diff > tolerance)
        print(f"  ❌ Channel {channel} ({name}): Max diff = {max_diff:.4f}")
        print(f"      Diff locations: {diff_locs[:5]}...")  # First 5
        return False
    else:
        print(f"  ✅ Channel {channel} ({name}): OK (max diff = {max_diff:.6f})")
        return True


def run_comparison(scenario):
    """Run full comparison for a scenario."""
    print(f"\n{'='*60}")
    print(f"  Scenario: {scenario}")
    print(f"{'='*60}")
    
    state = create_test_state(scenario)
    
    py_tensor = get_python_tensor(state)
    cpp_tensor = get_cpp_tensor(state)
    
    if cpp_tensor is None:
        print("  ⚠️  C++ returned no tensor (terminal state?)")
        return True  # Not a failure, just edge case
    
    print(f"  Python shape: {py_tensor.shape}")
    print(f"  C++ shape:    {cpp_tensor.shape}")
    
    if py_tensor.shape != cpp_tensor.shape:
        print(f"  ❌ SHAPE MISMATCH!")
        return False
    
    all_ok = True
    
    # Compare each channel group
    channel_names = [
        (0, "My Token 0"),
        (1, "My Token 1"),
        (2, "My Token 2"),
        (3, "My Token 3"),
        (4, "Opp Next Density"),
        (5, "Opp Team Density"),
        (6, "Opp Prev Density"),
        (7, "Safe Zones"),
        (8, "My Home Path"),
        (9, "Next Home Path"),
        (10, "Team Home Path"),
        (11, "Prev Home Path"),
        (12, "Dice=1"),
        (13, "Dice=2"),
        (14, "Dice=3"),
        (15, "Dice=4"),
        (16, "Dice=5"),
        (17, "Dice=6"),
        (18, "Score Diff"),
        (19, "My Locked"),
        (20, "Opp Locked"),
    ]
    
    for ch, name in channel_names:
        if not compare_channels(py_tensor, cpp_tensor, ch, name):
            all_ok = False
    
    return all_ok


def main():
    print("="*70)
    print("  DEEP TENSOR CONSISTENCY TEST: Python vs C++")
    print("="*70)
    
    scenarios = ["initial", "mid_game", "player1_view", "end_game"]
    results = {}
    
    for scenario in scenarios:
        results[scenario] = run_comparison(scenario)
    
    print("\n" + "="*70)
    print("  SUMMARY")
    print("="*70)
    
    all_passed = True
    for scenario, passed in results.items():
        status = "✅ PASSED" if passed else "❌ FAILED"
        print(f"  {scenario}: {status}")
        if not passed:
            all_passed = False
    
    if all_passed:
        print("\n✅ ALL SCENARIOS PASSED - C++ and Python tensors are consistent!")
        return 0
    else:
        print("\n❌ SOME SCENARIOS FAILED - C++ and Python tensors differ!")
        return 1


if __name__ == "__main__":
    exit(main())
